# Generated by Django 5.2.17 on 2026-09-06 23:14

import verification.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verificationrequest',
            options={'permissions': [('review_verificationrequest', 'Can review verification requests')]},
        ),
        migrations.AlterField(
            model_name='verificationdocument',
            name='file',
            field=models.FileField(storage=verification.storage.PrivateVerificationStorage(), upload_to='verification/%Y/%m/'),
        ),
    ]
