# Generated by Django 5.2.17 on 2026-09-07 00:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agencies", "0003_agency_country_code"),
        ("properties", "0004_propertylisting_country_code_and_more"),
        ("stays", "0004_stay_country_code_stay_stays_stay_status_70082d_idx_and_more"),
        ("verification", "0002_alter_verificationrequest_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="verificationrequest",
            index=models.Index(fields=["status", "submitted_at"], name="verificatio_status_b771d1_idx"),
        ),
    ]
