# Generated by Django 5.2.17 on 2026-09-06 21:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0002_seed_amenities'),
        ('stays', '0002_seed_stay_amenities'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='properties.propertylisting')),
                ('stay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='stays.stay')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('property__isnull', False), ('stay__isnull', True)), models.Q(('property__isnull', True), ('stay__isnull', False)), _connector='OR'), name='favourite_exactly_one_target'), models.UniqueConstraint(condition=models.Q(('property__isnull', False)), fields=('user', 'property'), name='unique_user_property_favourite'), models.UniqueConstraint(condition=models.Q(('stay__isnull', False)), fields=('user', 'stay'), name='unique_user_stay_favourite')],
            },
        ),
    ]
