from base64 import b64decode

from django.core.files.base import ContentFile

DEMO_IMAGE_BYTES = b64decode(
    "iVBORw0KGgoAAAANSUhEUgAAASwAAADICAYAAABS39xVAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJ"
    "bWFnZVJlYWR5ccllPAAAAlRJREFUeNrs1MENgCAQBEH5d4cCpQKC9AgzELBLTJiZZmZ2fJw5b9+n"
    "YwH8z8QBQBAEQAABBEAAAQQQAAGEEQABBEAAAQQQAAGEEQABBEAAAQQQAAGEEQABBEAAAQQQAAGE"
    "EQABBEAAAQQQAAGEEQABBEAAAQQQAAGEEQABBEAAAQQQAAGEEQABBEAAAQQQAAGEEQABBEAAAQQQ"
    "AAGEEQABBEAAAQQQAAGEEQABBEAAAQQQAAGEEQABBEAAAQQQAAGEEQABBEAAAQQQAAGEEQABBEAA"
    "AQQQAAGEEQABBEAAAQQQAAGEEQABBEAAAQQQAAGEEQABBEAAAQQQAAGEEQABBEAAAQQQAAGEEQAB"
    "BEAAAQQQAAGEEQABBEAAAQQQAAGEEQABBEAAAQQQAAGEEQABBEAAAQQQAAGEEQABBEAAAQQQAAGE"
    "EQABBEAAAQQQAAGEEQABBEAAAQQQAAGEEQABBEAAAQQQAAGEEQABBEAAAQQQAAGEEQABBEAAAQQQ"
    "AAGEEQABBEAAAQQQAAGEEQABBEAAAQQQAAGEEQABBEAAAQQQAAGEEQABBEAAAQQQAAGEEQABBEAA"
    "AQQQAAGEEQABBEAAAQQQAAGEEQABBEAAAQQQAAGEEQABBEAAAQQQAAGEEQABBEAAAQQQAAGEEQAB"
    "BEAAAQQQAAGEEQABBEAAAQQQAAGEEQABBEAAAQQQAAGEEQABBEAAAQQQAAGEEQABBEAAAQQQAAGE"
    "EQABBEAAAQQQAAGEEQABBEAAAQQQAAGEEQABBEAAAQQQAAGEEQABBEAAAQQQAAGEEQABBEAAAQQQ"
    "AAGEEQABBEAAAQQQAAGEEQABBEAAAQQQAAGEEQABBEAAAQQQAAGEEQABBEAAAQQQAAGEEQABBEAA"
    "AQQQAAGEEQABBEAAAQQQAAGEEQABBEAAAQQQAAGEEQABBEAAAQQQAAGEEQABBEAAAQQQAAGEEQAB"
    "BEAAAQQQAAGEEQABBEAAAQQQAAGEEQABBEAAAQQQAAGEEQABBEAAAQQQAAGEEQABBEAAAQQQAAGE"
    "EQABBEAAAQQQAAGEEQABBEAAAQQQAAGEEQABBEAAAQQQAAGEEQABBEAAAQQQAAGEEQABBEAAAQQQ"
    "AAGEEQABBEAAAQQQAAG+BAABNgMIXoGePgAAAABJRU5ErkJggg=="
)

PROPERTY_IMAGE_CAPTIONS = ["Exterior", "Living area", "Kitchen", "Bedroom", "Garden", "Neighbourhood"]
STAY_IMAGE_CAPTIONS = ["Exterior", "Guest room", "Lounge", "Dining", "Garden", "View"]
ROOM_IMAGE_CAPTIONS = ["Room", "Bathroom", "Sleeping area"]


def demo_image_file(name):
    return ContentFile(DEMO_IMAGE_BYTES, name=name)
