# Generated by Django 5.2.17 on 2026-09-06 21:30

import django.core.validators
import django.db.models.deletion
import properties.fields
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StayAmenity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'stay amenities',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(editable=False, max_length=30, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(editable=False, max_length=280, unique=True)),
                ('description', models.TextField(blank=True)),
                ('stay_type', models.CharField(choices=[('HOTEL', 'Hotel'), ('GUEST_HOUSE', 'Guest house'), ('LODGE', 'Lodge'), ('BNB', 'B&B'), ('SELF_CATERING', 'Self catering'), ('SHORT_STAY', 'Short stay'), ('RESORT', 'Resort'), ('HOSTEL', 'Hostel'), ('OTHER', 'Other')], max_length=20)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('town', models.CharField(blank=True, max_length=100)),
                ('suburb', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('location', properties.fields.location_field()),
                ('phone', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message='Enter a phone number in international format, for example +26876123456.', regex='^\\+[1-9]\\d{7,14}$')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('whatsapp_number', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message='Enter a phone number in international format, for example +26876123456.', regex='^\\+[1-9]\\d{7,14}$')])),
                ('website', models.URLField(blank=True)),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], default='UNVERIFIED', max_length=16)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under review'), ('PUBLISHED', 'Published'), ('PAUSED', 'Paused'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], default='DRAFT', max_length=16)),
                ('featured', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stays', to='agencies.agency')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stays', to='agencies.agentprofile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stays', to=settings.AUTH_USER_MODEL)),
                ('amenities', models.ManyToManyField(blank=True, related_name='stays', to='stays.stayamenity')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('capacity_adults', models.PositiveSmallIntegerField(default=1)),
                ('capacity_children', models.PositiveSmallIntegerField(default=0)),
                ('total_capacity', models.PositiveSmallIntegerField(default=1)),
                ('number_of_beds', models.PositiveSmallIntegerField(default=1)),
                ('bed_configuration', models.CharField(blank=True, max_length=255)),
                ('bathroom_type', models.CharField(blank=True, max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('currency', models.CharField(default='SZL', max_length=3)),
                ('minimum_stay', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='stays.stay')),
            ],
            options={
                'ordering': ['base_price', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StayImage',
            fields=[
                ('image', models.ImageField(upload_to='stays/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_cover', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='stays.stay')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoomAvailability',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('available_units', models.PositiveIntegerField()),
                ('custom_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('minimum_stay_override', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_blocked', models.BooleanField(default=False)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='stays.roomtype')),
            ],
            options={
                'ordering': ['date'],
                'constraints': [models.UniqueConstraint(fields=('room_type', 'date'), name='unique_room_availability_date')],
            },
        ),
        migrations.CreateModel(
            name='RoomTypeImage',
            fields=[
                ('image', models.ImageField(upload_to='stays/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_cover', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='stays.roomtype')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_cover', True)), fields=('room_type',), name='one_cover_per_room')],
            },
        ),
        migrations.AddConstraint(
            model_name='roomtype',
            constraint=models.UniqueConstraint(fields=('stay', 'slug'), name='unique_room_slug_per_stay'),
        ),
        migrations.AddIndex(
            model_name='stay',
            index=models.Index(fields=['status', '-created_at'], name='stays_stay_status_c01763_idx'),
        ),
        migrations.AddIndex(
            model_name='stay',
            index=models.Index(fields=['region', 'town', 'suburb'], name='stays_stay_region_9f15ed_idx'),
        ),
        migrations.AddConstraint(
            model_name='stayimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_cover', True)), fields=('stay',), name='one_cover_per_stay'),
        ),
    ]
