# Generated by Django 5.2.17 on 2026-09-06 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stays', '0002_seed_stay_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtypeimage',
            name='image',
            field=models.ImageField(upload_to='sureplace/rooms/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='stayimage',
            name='image',
            field=models.ImageField(upload_to='sureplace/stays/%Y/%m/'),
        ),
    ]
