# Generated by Django 5.2.17 on 2026-09-07 00:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agencies", "0003_agency_country_code"),
        ("stays", "0003_alter_roomtypeimage_image_alter_stayimage_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="stay",
            name="country_code",
            field=models.CharField(default="SZ", max_length=2),
        ),
        migrations.AddIndex(
            model_name="stay",
            index=models.Index(fields=["status", "-published_at"], name="stays_stay_status_70082d_idx"),
        ),
        migrations.AddIndex(
            model_name="stay",
            index=models.Index(fields=["stay_type", "status"], name="stays_stay_stay_ty_5c0a5b_idx"),
        ),
        migrations.AddIndex(
            model_name="stay",
            index=models.Index(fields=["featured", "status"], name="stays_stay_feature_2ccdb2_idx"),
        ),
    ]
