# Generated by Django 5.2.17 on 2026-09-13 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stays", "0004_stay_country_code_stay_stays_stay_status_70082d_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stay",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
