# Generated by Django 5.2.17 on 2026-10-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stays", "0005_stay_submitted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="stay",
            name="booking_mode",
            field=models.CharField(
                choices=[("REQUEST_TO_BOOK", "Request to Book"), ("INSTANT_BOOK", "Instant Book")],
                default="REQUEST_TO_BOOK",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="stay",
            name="cancellation_policy",
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name="stay",
            name="house_rules",
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
