# Generated by Django 5.2.17 on 2026-09-06 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_seed_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(upload_to='sureplace/properties/%Y/%m/'),
        ),
    ]
