# Generated by Django 5.2.17 on 2026-09-07 00:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agencies", "0003_agency_country_code"),
        ("properties", "0003_alter_propertyimage_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="propertylisting",
            name="country_code",
            field=models.CharField(default="SZ", max_length=2),
        ),
        migrations.AddIndex(
            model_name="propertylisting",
            index=models.Index(fields=["status", "-published_at"], name="properties__status_531703_idx"),
        ),
        migrations.AddIndex(
            model_name="propertylisting",
            index=models.Index(fields=["featured", "status"], name="properties__feature_d7b586_idx"),
        ),
    ]
