# Generated by Codex on 2026-09-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0004_propertylisting_country_code_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="propertylisting",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("review_propertylisting", "Can review property listings"),
                    ("approve_propertylisting", "Can approve property listings"),
                    ("request_changes_propertylisting", "Can request changes on property listings"),
                    ("reject_propertylisting", "Can reject property listings"),
                    ("suspend_propertylisting", "Can suspend property listings"),
                    ("restore_propertylisting", "Can restore property listings"),
                    ("add_note_propertylisting", "Can add property moderation notes"),
                ],
            },
        ),
        migrations.AlterField(
            model_name="propertylisting",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("SUBMITTED", "Submitted"),
                    ("UNDER_REVIEW", "Under review"),
                    ("PUBLISHED", "Published"),
                    ("CHANGES_REQUESTED", "Changes requested"),
                    ("PAUSED", "Paused"),
                    ("EXPIRED", "Expired"),
                    ("REJECTED", "Rejected"),
                    ("SUSPENDED", "Suspended"),
                ],
                default="DRAFT",
                max_length=24,
            ),
        ),
    ]
