# Generated by Django 5.2.17 on 2026-09-06 20:55

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='agencies/logos/')),
                ('description', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message='Enter a phone number in international format, for example +26876123456.', regex='^\\+[1-9]\\d{7,14}$')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('whatsapp_number', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message='Enter a phone number in international format, for example +26876123456.', regex='^\\+[1-9]\\d{7,14}$')])),
                ('website', models.URLField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('town', models.CharField(blank=True, max_length=100)),
                ('verification_status', models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], default='UNVERIFIED', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'agencies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bio', models.TextField(blank=True)),
                ('professional_reference', models.CharField(blank=True, max_length=255)),
                ('whatsapp_number', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message='Enter a phone number in international format, for example +26876123456.', regex='^\\+[1-9]\\d{7,14}$')])),
                ('verification_status', models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], default='UNVERIFIED', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='agencies.agency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['agency__name', 'user__email'],
                'constraints': [models.UniqueConstraint(fields=('user', 'agency'), name='unique_user_agency_profile')],
            },
        ),
    ]
