# Generated by Django 5.2.17 on 2026-09-06 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='sureplace/agencies/logos/'),
        ),
    ]
