# Generated by Django 5.2.17 on 2026-09-07 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agencies", "0002_alter_agency_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="agency",
            name="country_code",
            field=models.CharField(default="SZ", max_length=2),
        ),
    ]
