# Generated by Django 5.2.17 on 2026-09-07 00:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agencies", "0003_agency_country_code"),
        ("messaging", "0001_initial"),
        ("properties", "0004_propertylisting_country_code_and_more"),
        ("stays", "0004_stay_country_code_stay_stays_stay_status_70082d_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(fields=["-last_message_at"], name="messaging_c_last_me_3f31f1_idx"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["conversation", "created_at"], name="messaging_m_convers_7bc91b_idx"),
        ),
    ]
