# Generated by Django 5.2.17 on 2026-09-06 23:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
        ('properties', '0002_seed_amenities'),
        ('stays', '0002_seed_stay_amenities'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingreport',
            name='reason',
            field=models.CharField(choices=[('SCAM', 'Scam'), ('DUPLICATE', 'Duplicate'), ('INCORRECT', 'Incorrect information'), ('UNAVAILABLE', 'Unavailable'), ('INAPPROPRIATE', 'Inappropriate content'), ('OTHER', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='listingreport',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('UNDER_REVIEW', 'Under review'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], default='OPEN', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='listingreport',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('property__isnull', False), ('stay__isnull', True)), models.Q(('property__isnull', True), ('stay__isnull', False)), _connector='OR'), name='report_exactly_one_listing'),
        ),
    ]
