# Generated by Django 5.2.17 on 2026-09-06 21:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0002_seed_amenities'),
        ('stays', '0002_seed_stay_amenities'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('search_type', models.CharField(choices=[('PROPERTY', 'Property'), ('STAY', 'Stay')], max_length=10)),
                ('criteria', models.JSONField(default=dict)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('frequency', models.CharField(choices=[('INSTANT', 'Instant'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('OFF', 'Off')], default='DAILY', max_length=10)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_notified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchAlertEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('listing_type', models.CharField(choices=[('PROPERTY', 'Property'), ('STAY', 'Stay')], max_length=10)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_events', to='properties.propertylisting')),
                ('saved_search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='alerts.savedsearch')),
                ('stay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_events', to='stays.stay')),
            ],
            options={
                'ordering': ['-discovered_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('property__isnull', False), ('stay__isnull', True)), models.Q(('property__isnull', True), ('stay__isnull', False)), _connector='OR'), name='alert_exactly_one_target'), models.UniqueConstraint(condition=models.Q(('property__isnull', False)), fields=('saved_search', 'property'), name='unique_search_property_event'), models.UniqueConstraint(condition=models.Q(('stay__isnull', False)), fields=('saved_search', 'stay'), name='unique_search_stay_event')],
            },
        ),
    ]
