# Generated by Django 5.2.17 on 2026-09-06 21:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewingRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_date', models.DateField()),
                ('requested_time', models.TimeField()),
                ('alternative_date', models.DateField(blank=True, null=True)),
                ('alternative_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('RESCHEDULE_REQUESTED', 'Reschedule requested')], default='PENDING', max_length=24)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viewing_requests', to='agencies.agentprofile')),
            ],
            options={
                'ordering': ['requested_date', 'requested_time'],
            },
        ),
    ]
