# Generated by Django 5.2.17 on 2026-09-06 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('messaging', '0001_initial'),
        ('properties', '0002_seed_amenities'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='viewingrequest',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viewing_requests', to='messaging.conversation'),
        ),
        migrations.AddField(
            model_name='viewingrequest',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewing_requests', to='properties.propertylisting'),
        ),
        migrations.AddField(
            model_name='viewingrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewing_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='viewingrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'CONFIRMED', 'RESCHEDULE_REQUESTED'])), fields=('property', 'requester', 'requested_date', 'requested_time'), name='unique_active_viewing_request'),
        ),
    ]
