# Generated by Django 5.2.17 on 2026-09-06 22:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
        ('messaging', '0001_initial'),
        ('stays', '0002_seed_stay_amenities'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(editable=False, max_length=32, unique=True)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('adults', models.PositiveSmallIntegerField()),
                ('children', models.PositiveSmallIntegerField(default=0)),
                ('rooms', models.PositiveSmallIntegerField()),
                ('nightly_pricing', models.JSONField(default=list)),
                ('nightly_subtotal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('taxes', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('fees', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='SZL', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired')], default='PENDING', max_length=12)),
                ('payment_status', models.CharField(choices=[('NOT_REQUIRED', 'Not required'), ('UNPAID', 'Unpaid'), ('PARTIALLY_PAID', 'Partially paid'), ('PAID', 'Paid'), ('REFUNDED', 'Refunded'), ('FAILED', 'Failed')], default='UNPAID', max_length=20)),
                ('guest_name', models.CharField(max_length=200)),
                ('guest_email', models.EmailField(max_length=254)),
                ('guest_phone', models.CharField(blank=True, max_length=20)),
                ('special_requests', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=100, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='messaging.conversation')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stay_bookings', to=settings.AUTH_USER_MODEL)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='stays.roomtype')),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='stays.stay')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('guest', 'idempotency_key'), name='unique_guest_booking_idempotency')],
            },
        ),
    ]
