# Generated by Django 5.2.17 on 2026-09-07 00:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_booking"),
        ("messaging", "0002_conversation_messaging_c_last_me_3f31f1_idx_and_more"),
        ("stays", "0004_stay_country_code_stay_stays_stay_status_70082d_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["guest", "-created_at"], name="bookings_bo_guest_i_75f949_idx"),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["stay", "status"], name="bookings_bo_stay_id_3ec825_idx"),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["room_type", "check_in", "check_out"], name="bookings_bo_room_ty_86afe5_idx"),
        ),
    ]
