# Generated by Django 5.2.17 on 2026-10-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_booking_bookings_bo_guest_i_75f949_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="action_note",
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="booking",
            name="booking_mode",
            field=models.CharField(default="REQUEST_TO_BOOK", max_length=20),
        ),
        migrations.AddField(
            model_name="booking",
            name="cancellation_reason",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="booking",
            name="decline_reason",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="booking",
            name="payment_method",
            field=models.CharField(default="PAY_AT_PROPERTY", max_length=24),
        ),
        migrations.AddField(
            model_name="booking",
            name="policy_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
