# Generated by Django 5.2.17 on 2026-09-06 22:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_enabled', models.BooleanField(default=True)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('new_message_email', models.BooleanField(default=True)),
                ('viewing_updates_email', models.BooleanField(default=True)),
                ('booking_updates_email', models.BooleanField(default=True)),
                ('saved_search_email', models.BooleanField(default=True)),
                ('listing_reminders_email', models.BooleanField(default=True)),
                ('marketing_email', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('NEW_MESSAGE', 'New message'), ('GUEST_ENQUIRY', 'Guest enquiry'), ('VIEWING_REQUEST', 'Viewing request'), ('VIEWING_CONFIRMED', 'Viewing confirmed'), ('VIEWING_RESCHEDULED', 'Viewing rescheduled'), ('VIEWING_CANCELLED', 'Viewing cancelled'), ('BOOKING_REQUESTED', 'Booking requested'), ('BOOKING_CONFIRMED', 'Booking confirmed'), ('BOOKING_DECLINED', 'Booking declined'), ('BOOKING_CANCELLED', 'Booking cancelled'), ('BOOKING_EXPIRING', 'Booking expiring'), ('SAVED_SEARCH_MATCH', 'Saved-search match'), ('LISTING_AVAILABILITY_REMINDER', 'Availability reminder'), ('LISTING_STATUS_UPDATE', 'Listing status'), ('VERIFICATION_UPDATE', 'Verification'), ('SYSTEM', 'System')], max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('event_key', models.CharField(blank=True, max_length=200, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('event_key__isnull', False)), fields=('user', 'event_key'), name='unique_notification_event')],
            },
        ),
    ]
