# Generated by Codex on 2026-09-08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_notification_notificatio_user_id_f2ad08_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailDelivery",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("recipient", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=998)),
                ("provider", models.CharField(blank=True, max_length=40)),
                ("provider_message_id", models.CharField(blank=True, max_length=120)),
                ("template_key", models.CharField(default="transactional", max_length=80)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("accepted", "Accepted"), ("failed", "Failed")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("last_error_code", models.CharField(blank=True, max_length=100)),
                ("last_error_message", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "notification",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_deliveries",
                        to="notifications.notification",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["provider", "provider_message_id"], name="notificati_provide_e9f577_idx"),
                    models.Index(fields=["status", "-created_at"], name="notificati_status_24f7ea_idx"),
                ],
            },
        ),
    ]
