# Generated by Django 5.2.17 on 2026-10-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("NEW_MESSAGE", "New message"),
                    ("GUEST_ENQUIRY", "Guest enquiry"),
                    ("VIEWING_REQUEST", "Viewing request"),
                    ("VIEWING_CONFIRMED", "Viewing confirmed"),
                    ("VIEWING_RESCHEDULED", "Viewing rescheduled"),
                    ("VIEWING_CANCELLED", "Viewing cancelled"),
                    ("BOOKING_REQUESTED", "Booking requested"),
                    ("BOOKING_CONFIRMED", "Booking confirmed"),
                    ("BOOKING_DECLINED", "Booking declined"),
                    ("BOOKING_CANCELLED", "Booking cancelled"),
                    ("BOOKING_EXPIRING", "Booking expiring"),
                    ("BOOKING_EXPIRED", "Booking expired"),
                    ("BOOKING_REQUEST_SUBMITTED", "Booking request submitted"),
                    ("BOOKING_REMINDER", "Upcoming stay"),
                    ("BOOKING_INSTANT_CONFIRMED", "Instant booking confirmed"),
                    ("SAVED_SEARCH_MATCH", "Saved-search match"),
                    ("LISTING_AVAILABILITY_REMINDER", "Availability reminder"),
                    ("LISTING_STATUS_UPDATE", "Listing status"),
                    ("VERIFICATION_UPDATE", "Verification"),
                    ("SYSTEM", "System"),
                ],
                max_length=40,
            ),
        ),
    ]
